#+TITLE: Autosubst OCaml

* Setup
** Switch
#+BEGIN_SRC bash
opam switch create autosubst-ocaml ocaml-base-compiler.4.11.1
opam repo add coq-released https://coq.inria.fr/opam/released
opam install dune coq.8.12.1
#+END_SRC

** build dependencies
#+BEGIN_SRC bash
opam install angstrom lwt ocamlgraph ppx_deriving ppx_compare ppx_fields_conv
#+END_SRC

** dev dependencies
#+BEGIN_SRC bash
opam install merlin utop ocp-indent ocamlformat
#+END_SRC

* Build & Run
#+BEGIN_SRC bash
dune build
dune exec -- bin/main.exe <signature file> <output file> [coq|ucoq]
# e.g. dune exec -- bin/main.exe signatures/fol.sig case-studies/fol/fol_wellscoped.v coq
#+END_SRC
* Repo
You can find the code at https://gitlab.com/addapp/autosubst-ocaml
* Demo
The demos are generated by the generate.sh. They can be found in case-studies/
** examples/
contains just the generated sources for a couple of different signatures. You can issue `make` in this directory to have Coq compile all the files. The lemmas/definitions/fixpoints are equivalent to those generated by Autosubst2. The classes/instances/tactics are not generated.
** lfmtp/
contains the lfmtp case study by Kathrin Stark where a couple of metatheoretic theorems are proved about stlc & fcbv. The case study was originally for Coq 8.9 and due to different handling of implicit arguments it does not work directly with Coq 8.12.1, so to run this we install Coq 8.9 on a different switch.
#+BEGIN_SRC
opam switch create autosubst-ocaml ocaml-base-compiler.4.11.1
opam repo add coq-released https://coq.inria.fr/opam/released
opam install coq.8.9.1
#+END_SRC
You can also issue `make` there to have Coq compile all the files.
