#+Title Removing Functional Extensionality

This memo is concerned with removing the dependency on the functional extensionality axiom from the asimpl tactic provided by Autosubst.
It lists different appraoches and problems although they may not always be up to date to the state of the source code.

* Functional Extensionality (funext)
#+begin_src coq
Axiom funext : forall X Y (f g : X -> Y), (forall x, f x = g x) -> f = g.
#+end_src
Two functions are equal provided they are extensionally equal. It's consistent as an axiom in Coq (afaik the reasoning is there are no models of Coq's type theory that invalidate it).
However, some people don't want their development to contain these kinds of axioms. They should still be able to use automation tactics like asimpl to do the boilerplate proofs of subtitution equations.
* Where is it used?
We use funext for easier rewriting in the automation tactics. There are a number of lemmas stating the extensional equality of certain functions like
#+begin_src coq
Lemma scons_comp (t: tm) (f: nat -> tm) (g: tm -> tm) :
  forall n, ((t .: f) >> g) x = (t[g] .: f >> g) x.
#+end_src
that are part of the equational theory of the deBruijn algebra at hand. Using funext we can then easily rewrite the function on the left-hand side to the function on the right-hand side as in the following instantiation.
#+begin_src coq
s[(t .: var_tm) >> f] ~~> s[t[f] .: var_tm >> f]
#+end_src
However, funext does not give us more power in this case because we can also prove a lemma stating that instantiations with extensionally equal functions are equal. Intuitively is makes sense because a subsitution replaces all free variables in a term, i.e. if all free variables are replaced by the same terms respectively, the instantiations have the same result.
#+begin_src coq
Lemma ext_tm (s: tm) (f g : nat -> tm) :
  (forall n, f n = g n) -> s[f] = s[g]
#+end_src
But it certainly is more convenient using funext because we can use the normal rewriting facilities to swap out one function for another, whereas with this lemma we need to explicitly apply it and then argue why the substitutions are extensionally equal (and the function we want to replace might be a subterm of the whole subsitution so we first need to find it).
* Replace with Setoid Rewriting
As already explained, a disadvantage of using the ext_tm lemma manually is that it talks about the whole subsitution whereas we might only want to replace a subterm (substitutions can generally be composed of opaque functions `f`, scons `.:` and function composition `>>`).
One approach is to use setoid rewriting to automatically derive a rewriting strategy that replaces that one subterm while leaving everyting else in place.
With setoid rewriting we can specify the ext_tm lemma (and similar lemmas) as so-called morphisms which are then automatically used to staisfy constraints for the rewriting.
E.g. if we want to replace the function f with g in the following instantiation
#+begin_src coq
s[t .: f >> h] ~~> s[t .: g >> h]
#+end_src
We first need a morphism allowing us to rewrite the substitution with an extensionally equal one resulting in an equal instantiation and then morphisms for .: and >> that allow us to replace a subterm of a substitution with an extensionally equal one resulting in an extensionally equal subsitution.
For the user it essentially suffices to write `setoid_rewrite H` where H as type (forall x, f x = g x) and the subterm is replaced. There is one problem though, it appears we need a syntactic match for the rewrite to happen, which often necessitates unfolding function composition so that functions are applied to an argument.
E.g. in the below term we have `f x` so that we can rewrite with above H.
#+begin_src coq
s[t .: (fun x => h (f x))]
#+end_src
** What is needed to change?
*** Lemmas
For stlc we need 5 new lemmas, or rather new versions of 5 lemmas that stated an equality between functions before and now state an extensional equality
1. varL : var >> [sigma] == sigma
2. varLRen : var >> <xi> == xi >> var
3. rinstInst : <xi> = [xi >> var]
4. rinstId : <id> == id
5. instId : [var] == id
It should be 5 lemmas per sort that has variables. All of them have very short and mechanical proof scripts so it should be easy to generate.
*** Proper Instances
The morphisms are instances of the Proper typeclass. We can use Coq's pretty printer to print the Instance declarations.
They also have very simple and mechanical proof terms because there is one instance per renaming/subsitution function and they are basically the extensionality lemmas we already generate. The morphisms for scons/scons_p are general enough to be in the static files.
*** Tactic
We can use an ltac script that is very similar to the original asimpl. This is because whenever we could write `rewrite X` to replace a function in the original asimpl we can write `setoid_rewrite X'` with X' being an extensional version of X.
Also we completely unfold function composition as discussed in the next section.
**** TODO check if there are pathologic cases where we don't have funcomp and would need to eta expand
** Problems with function composition
We unfold it because setoid rewrite needs a syntactic match to start the rewrite (i.e. if we rewrite with something of type `f x = g x`, then we need f applied to x somewhere in the term, and `f >> g` unfolded contains such a subterm.)
This is a bit unsatisfactory because the morphism for subst ((forall x, f x = g x) -> s[f] = s[g]) already gives you such a subterm but setoid rewrite needs `f x` before it even thinks about using that morphism.
There is also another point in favor of unfolding function composition. There are cases where setoid rewrite fails if the term contains too many function compositions (even though a morphism exists). There should be an instance in the coq-setoid-asimpl copy of Kathrin's case study.
** Problem with eta-expanded functions
A description is in the [[file:../case-studies/kathrin/coq-setoid/Chapter9/testbench.v][source code]] in the MWE module. The heuristics used by setoid rewriting apparently does not lile rewriting under eta-expanded functions.
This is however not a problem since we can eta-reduce these functions to be able to proceed with rewriting.
*** DONE check morphism for eta-expanded functions
No it does not work to define a morphism for eta expanded functions. I don't think the setoid rewrite mechanism looks at binders this way, rather it only checks if a morphism exists for the outermost function symbol. But I did not finish the paper about it.
I think I already tried that but check again.
*** TODO check the paper if they say anything about eta expansion there
Iirc they say rewriting under binders is possible, which this is an instance of.

* Replace with Guided Applications of ext_tm
Since setoid rewriting is pretty slow we can also try to manually apply ext_tm guided by some heuristics. This would then be faster since we only apply ext_tm once at the beginning and then bit-by-bit prove the extensional equality of the two substitutions using other rewriting lemmas instead of using it once every time we rewrite anything inside a substitution.
This works already pretty well for goals involving an equation. However, this method is currently not suited to normalize a given term (which sometimes is necessary if a term appears as an index of some other type, like a type assignment predicate)
This is because in these cases, rewriting with ext_tm results in a goal of the form `s[f] = ?e` and normal rewriting is too naive because it does spurious rewrites on the right with the evar which then results in a non-normal term.
** One solution might be to use a technique similar to the `under` tactic (or use the tactic itself)
https://coq.inria.fr/refman/proof-engine/ssreflect-proof-language.html#coq:tacn.under
[[file:~/programming/bachelor/autosubst3/case-studies/kathrin/coq-ext/Chapter9/testbench.v][Using the under tactic]] kind of works. Instead of rewriting with the extensionality lemmas, we pass them to under and can then rewrite with our normal lemmas. (under requires ssreflect though so the rewrite is the one from there which is more powerful)
Under the hood the under tatic seems to use a generic relation which wraps the relation in the conclusion, i.e. `s[f] = x` turns into `Under_rel eq (s[f]) x` and then probably uses some kind of morphism so that any rewrite we do only applies to the left-hand side.
** Another might be to use the fast funext based asimpl
We could use it purely to compute the normal form `t` of a term `s` and then assert the equation `s = t` which is then provable by the non-funext asimpl.
We would need to take special care that the funext asimpl never actually appears in the proof term.
